name:                Hastructure
version:	 0.45.0
github:              "yellowbean/Hastructure"
license:             BSD3
author:              "Xiaoyu"
maintainer:          "always.zhang@gmail.com"
copyright:           "2025 Xiaoyu, Zhang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            StructuredFinance;Securitisation;Cashflow

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yellowbean/Hastructure#readme>

dependencies:
- base
- hashable
- time 
- lens
- generic-lens
- aeson
- aeson-pretty
- text
- bytestring
- template-haskell
- containers
- regex-tdfa
- regex-base
- regex-pcre-builtin
- vector
- wai
- monad-loops
- ieee754
- servant
- servant-server
- servant-openapi3
- openapi3
- swagger2
- split
- yaml
- lucid
- tabular
- numeric-limits
- scientific
- math-functions
- parallel
- deepseq
- mtl

library:
  source-dirs: 
   - src

executables:
  Hastructure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hastructure  
    - time
    - aeson
    - attoparsec-aeson
    - text 
    - containers
    - unordered-containers
    - containers
    - warp
    - wai-cors
    - base-compat  
    - http-types
    - template-haskell
    - yaml
    - scientific
    - openapi3
    - servant-server
    - mtl
    - servant
    - lucid
    - monad-loops
    - string-conversions
    - attoparsec
    - exceptions
    - tabular
    - math-functions
    - servant-checked-exceptions

tests:
  Hastructure-test:
    main:                MainTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hastructure
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-golden


allow-newer: true
